"""Storage for recordings and protocol files, kept under DATA_DIR. Keys are always generated by the server, e.g. `audio/<id>.mp3` or
`protocols/<id>/v3.pdf`.
"""

import mimetypes
import re
import shutil
from pathlib import Path

KEY_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*")


def check_key(key: str) -> str:
    if len(key) > 500 or not KEY_PATTERN.fullmatch(key) or ".." in key:
        raise ValueError(f"Invalid storage key: {key!r}")
    return key


def media_type(key: str) -> str:
    return mimetypes.guess_type(key)[0] or "application/octet-stream"


class LocalBlobStore:
    kind = "local"

    def __init__(self, root: Path):
        self.root = root
        root.mkdir(parents=True, exist_ok=True)

    def prepare(self):
        pass

    def path(self, key):
        return self.root / check_key(key)

    def put_file(self, key, source: Path):
        """Store `source` under `key`. The source file is consumed."""
        target = self.path(key)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(source), target)

    def put_bytes(self, key, data: bytes):
        target = self.path(key)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)

    def get_bytes(self, key):
        return self.path(key).read_bytes()

    def local_path(self, key):
        path = self.path(key)
        return path if path.is_file() else None

    def open_stream(self, key, chunk_size=1 << 16):
        handle = self.path(key).open("rb")

        def chunks():
            with handle:
                while chunk := handle.read(chunk_size):
                    yield chunk

        return chunks()

    def checkout(self, key) -> Path:
        path = self.path(key)
        if not path.is_file():
            raise FileNotFoundError(key)
        return path

    def release(self, path: Path):
        pass

    def exists(self, key):
        return self.path(key).is_file()

    def delete(self, key):
        self.path(key).unlink(missing_ok=True)

    def delete_prefix(self, prefix):
        path = self.path(prefix.rstrip("/"))
        if path.is_dir():
            shutil.rmtree(path)


def make_blob_store(settings):
    return LocalBlobStore(settings.data_dir)
