"""Storage for recordings and approved protocol files.

MinIO (any S3-compatible service) is used when MINIO_ENDPOINT is set, otherwise files live
under DATA_DIR. Keys are always generated by the server, e.g. `audio/<id>.mp3` or
`protocols/<id>/v3.pdf`.
"""

import mimetypes
import os
import re
import shutil
import tempfile
from io import BytesIO
from pathlib import Path
from urllib.parse import urlparse

KEY_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*")


def check_key(key: str) -> str:
    if len(key) > 500 or not KEY_PATTERN.fullmatch(key) or ".." in key:
        raise ValueError(f"Invalid storage key: {key!r}")
    return key


def media_type(key: str) -> str:
    return mimetypes.guess_type(key)[0] or "application/octet-stream"


class LocalBlobStore:
    kind = "local"

    def __init__(self, root: Path):
        self.root = root
        root.mkdir(parents=True, exist_ok=True)

    def prepare(self):
        pass

    def path(self, key):
        return self.root / check_key(key)

    def put_file(self, key, source: Path):
        """Store `source` under `key`. The source file is consumed."""
        target = self.path(key)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(source), target)

    def put_bytes(self, key, data: bytes):
        target = self.path(key)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)

    def get_bytes(self, key):
        return self.path(key).read_bytes()

    def local_path(self, key):
        path = self.path(key)
        return path if path.is_file() else None

    def open_stream(self, key, chunk_size=1 << 16):
        handle = self.path(key).open("rb")

        def chunks():
            with handle:
                while chunk := handle.read(chunk_size):
                    yield chunk

        return chunks()

    def checkout(self, key) -> Path:
        path = self.path(key)
        if not path.is_file():
            raise FileNotFoundError(key)
        return path

    def release(self, path: Path):
        pass

    def exists(self, key):
        return self.path(key).is_file()

    def delete(self, key):
        self.path(key).unlink(missing_ok=True)

    def delete_prefix(self, prefix):
        path = self.path(prefix.rstrip("/"))
        if path.is_dir():
            shutil.rmtree(path)


class MinioBlobStore:
    kind = "minio"

    def __init__(self, endpoint, access_key, secret_key, bucket, secure, tmp_dir: Path):
        from minio import Minio

        parsed = urlparse(endpoint if "://" in endpoint else f"//{endpoint}")
        if parsed.scheme:
            secure = parsed.scheme == "https"
        self.client = Minio(parsed.netloc, access_key=access_key, secret_key=secret_key, secure=secure)
        self.bucket = bucket
        self.tmp_dir = tmp_dir
        tmp_dir.mkdir(parents=True, exist_ok=True)

    def prepare(self):
        if not self.client.bucket_exists(self.bucket):
            self.client.make_bucket(self.bucket)

    def put_file(self, key, source: Path):
        try:
            self.client.fput_object(self.bucket, check_key(key), str(source), content_type=media_type(key))
        finally:
            Path(source).unlink(missing_ok=True)

    def put_bytes(self, key, data: bytes):
        self.client.put_object(self.bucket, check_key(key), BytesIO(data), len(data), content_type=media_type(key))

    def get_bytes(self, key):
        response = self.client.get_object(self.bucket, check_key(key))
        try:
            return response.read()
        finally:
            response.close()
            response.release_conn()

    def local_path(self, key):
        return None

    def open_stream(self, key, chunk_size=1 << 16):
        response = self.client.get_object(self.bucket, check_key(key))

        def chunks():
            try:
                yield from response.stream(chunk_size)
            finally:
                response.close()
                response.release_conn()

        return chunks()

    def checkout(self, key) -> Path:
        descriptor, name = tempfile.mkstemp(dir=self.tmp_dir, suffix=Path(key).suffix)
        os.close(descriptor)
        try:
            self.client.fget_object(self.bucket, check_key(key), name)
        except BaseException:
            Path(name).unlink(missing_ok=True)
            raise
        return Path(name)

    def release(self, path: Path):
        path.unlink(missing_ok=True)

    def exists(self, key):
        from minio.error import S3Error

        try:
            self.client.stat_object(self.bucket, check_key(key))
            return True
        except S3Error as error:
            if error.code in {"NoSuchKey", "NoSuchObject", "NoSuchBucket"}:
                return False
            raise

    def delete(self, key):
        self.client.remove_object(self.bucket, check_key(key))

    def delete_prefix(self, prefix):
        from minio.deleteobjects import DeleteObject

        prefix = check_key(prefix.rstrip("/")) + "/"
        objects = [DeleteObject(item.object_name) for item in self.client.list_objects(self.bucket, prefix=prefix, recursive=True)]
        for error in self.client.remove_objects(self.bucket, objects):
            raise RuntimeError(f"Не удалось удалить {error.name}: {error.message}")


def make_blob_store(settings):
    if settings.minio_endpoint:
        return MinioBlobStore(
            settings.minio_endpoint,
            settings.minio_access_key,
            settings.minio_secret_key,
            settings.minio_bucket,
            settings.minio_secure,
            settings.data_dir / "tmp",
        )
    return LocalBlobStore(settings.data_dir)
